### ISSUE TITLE
1D Convolution op

### ISSUE THREAD

**Issue by dan-garvey** [nod-ai/SHARK-ModelDev#210]
: https://github.com/llvm/torch-mlir/blob/536e45cb3bc6951ae90de5c8e969d7fd03cfd955/lib/Conversion/TorchToLinalg/Linear.cpp#L533

**Comment by srcarroll** [comment]
I'm interested in adding support for this

**Comment by dan-garvey** [comment]
@stellaraccident can you add perms for Sam to accept issue assignment

**Comment by vivekkhandelwal1** [comment]
Hi @dan-garvey, can we close this issue, if fixed?
