### ISSUE TITLE
torch.aten.max_unpool2d

### ISSUE THREAD

**Issue by Hardcode84** [nod-ai/SHARK-ModelDev#764]

**Comment by Hardcode84** [comment]
PR for `max_unpool3d` was merged (https://github.com/nod-ai/SHARK-Turbine/issues/765), but unfortunately, this approach won't work for `max_unpool2d` as corresponding aten node preserve even less info than `max_unpool3d`, we need a different approach, either lowering directly to (parallel) `scf` loop or ONNX->linalg lowering, skipping aten op. See `max_unpool3d` issue and PR for details.

**Comment by vivekkhandelwal1** [comment]
Hi @Hardcode84, are you still working on this op?

**Comment by Hardcode84** [comment]
Hi, @vivekkhandelwal1, I did `max_unpool3d` but I'm not working on `max_unpool2d` currently.

**Comment by jinchen62** [comment]
Duplicate issue of https://github.com/nod-ai/SHARK-ModelDev/issues/718, so close this.
