### ISSUE TITLE
ConvTranspose (auto_pad)

### ISSUE THREAD

**Issue by zjgarvey** [nod-ai/SHARK-ModelDev#839]
~Assigned to Luka Tsabadze~

**Comment by guacamoleo** [comment]
Support (and testing) has been added for ConvTranspose autopadding. The remaining unsupported component is asymmetric padding; however asymmetric padding may be more pervasive than just ConvTranspose, so someone else should create an issue for it.

**Comment by guacamoleo** [comment]
Closing turbine camp issue.
